text = [	
        "Dane,",
        "",
        "dokázal jsi to. Vyřešil jsi problém, který nemá řešení,",
        "stačil jiný přístup. Věříme, že překážky, které tě",
        "po cestě sem potkávaly z tebe udělaly lepšího člověka, který ",
        "zde nyní stojí. Snad ti na cestě pomohli starší, kteří ti",
        "umožnili vybrousit dovednosti. Snad přátelé, kteří nepřestávali",
        "podporovat.",
        "",
        "Omlouváme se, že jsme chtěli obsadit Zemi, zotročit lidstvo a ",
        "překazit ti svatbu (což nechceš). Je údělem veškerého tvorstva",
        "se ve vypjatých situacích chovat nepřístojně k jiným, kteří nám",
        "mohou pomoci. Snad, až to jednou všichni pochopíme, bude vesmír ",
        "lepším místem. ",
        "",
        "Na tvoji počest vystavíme alej tvých soch. Kdyby jsi měl někdy",
        "cestu kolem, určitě se stav. Jsou odsud vidět úplně jiné hvězdy",
        "než ze Země nebo Měsíce. Do té doby ti naším Galaktickým Lineárním",
        "Superpaprskem (GLS) zasíláme propriety na hostinu. A na památku.",
        "",
        "Navždy sbohem,",
        "	navždy dík,",
        "		\033[93m Trisolarané \033[0m",
        "",
    ]